(function(g){
'use strict';
const VERSION='1.2.0',API='1.2.0',WIDTH=Object.freeze({min:180,standard:270,max:420,warning:20});
function normalizeWidth(value){return Math.max(WIDTH.min,Math.min(WIDTH.max,Number(value)||WIDTH.standard))}
function widthSignal(value){const n=Number(value);if(n<WIDTH.min||n>WIDTH.max)return'red';if(n<WIDTH.min+WIDTH.warning||n>WIDTH.max-WIDTH.warning)return'yellow';return'green'}
function create(){let adapter=null;const events=[];const emit=(type,data)=>events.push(Object.freeze({type,at:new Date().toISOString(),...(data||{})}));const need=()=>{if(!adapter)throw Error('NAVIGATION_CORE_ADAPTER_NOT_BOUND');return adapter};return Object.freeze({version:VERSION,apiVersion:API,widthPolicy:WIDTH,normalizeWidth,widthSignal,bindAdapter(a){if(!a||typeof a.setWidth!=='function'||typeof a.toggleQuick!=='function'||typeof a.resetWidth!=='function')throw Error('NAVIGATION_CORE_ADAPTER_INVALID');adapter=a;emit('ADAPTER_BOUND',{version:a.version||null});return true},isBound(){return!!adapter},setWidth(w,o){const normalized=normalizeWidth(w),r=need().setWidth(normalized,o);emit('WIDTH_SET',{requested:w,width:normalized,signal:widthSignal(w)});return r},toggleSidebar(){const r=need().toggleQuick();emit('SIDEBAR_TOGGLED');return r},resetWidth(){const r=need().resetWidth();emit('WIDTH_RESET',{width:WIDTH.standard});return r},snapshot(){return Object.freeze({version:VERSION,apiVersion:API,adapterBound:!!adapter,widthPolicy:WIDTH,eventCount:events.length})},eventLog(){return Object.freeze(events.slice())}})}
g.NavigationCore=Object.freeze({version:VERSION,apiVersion:API,widthPolicy:WIDTH,normalizeWidth,widthSignal,create});
g.NavigationCoreContract=Object.freeze({coreId:'NavigationCore',runtimeId:'master.navigation',version:VERSION,apiVersion:API,behaviorOwner:'central-core-runtime',features:Object.freeze(['resize-signal','standard-width-reset','width-lock-adapter','menu-state-adapter']),releaseGate:'YELLOW_REAL_DEVICE_EVIDENCE_OPEN'});
})(window);
