const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8");
const app=read("pc-manager/app.js");
const styles=read("pc-manager/styles.css");
const dashboard=read("pc-manager/manager-sales-inventory-dashboard.js");
const dashboardCss=read("pc-manager/manager-sales-inventory-dashboard.css");
const stockCore=read("cores/sales-inventory-analysis-core/sales-inventory-analysis-core.js");
const surfaces=read("pc-manager/tv-content-object-core-v02940.js");
const player=read("tv-player/tv-object-parity-v1.js");

assert.match(app,/labelSlideType\?\.\(k\)/,"TV-Dashboard muss Folientypen zentral deutsch benennen");
assert.match(stockCore,/pricelist:"Preisliste"/);
assert.match(stockCore,/program:"Bühnenprogramm"/);
assert.match(dashboard,/function completeStock/);
assert.match(dashboard,/kcStockSave/);
assert.match(dashboard,/kcStockClear/);
assert.match(dashboard,/kcGroupShareLegend/);
assert.match(dashboardCss,/kc-chart-legend/);
assert.match(styles,/#tvExportPackage,#tvDashExport/);
assert.match(styles,/\.split>\*\{min-width:0\}/);
assert.match(app,/gluehwein_rot_auth\.webp/);
assert.match(app,/fillRect\(288,26\+i\*25,13,13\)/,"Auch das Übersichts-Kreisdiagramm braucht farbige Legendenfelder");
assert.match(surfaces,/Glasrückwand/);
assert.match(surfaces,/mode==='glass'/);
assert.match(surfaces,/s\.objectStyles\[key\]=style/,"Neue Textflächen müssen am Folienobjekt gespeichert werden");
assert.match(player,/style\.surfaceMode/);
assert.match(player,/backdrop-filter/);
assert.match(read("pc-manager/tv-display-matrix-adapter.js"),/querySelectorAll\(':scope > \.kc-property-section,:scope > \.kc-ticker-advanced,:scope > \.kc-source-controls'\)/,"Der MatrixCore muss alle konkurrierenden Laufschriftfelder entfernen");
console.log("PASS Repair 58: Glasflächen, deutsche Folientypen, Legende, Bestandsliste, Layout und Artikelfotos");
