(function(g){
'use strict';
const WMO={0:['☀️','Klar'],1:['🌤️','Überwiegend klar'],2:['⛅','Teilweise bewölkt'],3:['☁️','Bedeckt'],45:['🌫️','Nebel'],48:['🌫️','Reifnebel'],51:['🌦️','Leichter Nieselregen'],53:['🌦️','Nieselregen'],55:['🌧️','Starker Nieselregen'],61:['🌦️','Leichter Regen'],63:['🌧️','Regen'],65:['🌧️','Starker Regen'],71:['🌨️','Leichter Schnee'],73:['🌨️','Schnee'],75:['❄️','Starker Schnee'],80:['🌦️','Regenschauer'],81:['🌧️','Regenschauer'],82:['⛈️','Starke Schauer'],95:['⛈️','Gewitter'],96:['⛈️','Gewitter mit Hagel'],99:['⛈️','Starkes Gewitter']};
const cache=new Map();
const KNOWN=[{name:'Werne',admin1:'Nordrhein-Westfalen',country:'Deutschland',latitude:51.6640,longitude:7.6342,timezone:'Europe/Berlin',label:'59368 Werne, Nordrhein-Westfalen, Deutschland',postalCode:'59368'}];
function mapCode(c){return WMO[c]||['🌡️','Wetterlage'];}
async function json(url,{timeout=8000,signal}={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);const onAbort=()=>ctl.abort();signal?.addEventListener('abort',onAbort,{once:true});try{const r=await fetch(url,{headers:{Accept:'application/json'},signal:ctl.signal,cache:'no-store'});if(!r.ok)throw new Error('Wetterdienst nicht erreichbar ('+r.status+').');return await r.json();}catch(e){if(e?.name==='AbortError')throw new Error('Wetterdienst antwortet zu langsam. Bitte erneut versuchen.');throw e;}finally{clearTimeout(timer);signal?.removeEventListener('abort',onAbort);}}
function knownPlace(q){const n=q.toLowerCase().replace(/\s+/g,' ');return KNOWN.find(x=>n.includes(x.name.toLowerCase())||n.includes(x.postalCode));}
async function searchPlaces(query,count=8,{signal}={}){const q=String(query||'').trim();if(q.length<2)return[];const known=knownPlace(q);if(known)return[known];const key='p:'+q.toLowerCase();if(cache.has(key))return cache.get(key);const data=await json('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count='+count+'&language=de&format=json',{timeout:6500,signal});const out=(data.results||[]).map(x=>({name:x.name,admin1:x.admin1||'',country:x.country||'',latitude:x.latitude,longitude:x.longitude,timezone:x.timezone||'auto',postalCode:x.postcodes?.[0]||'',label:[x.postcodes?.[0],x.name,x.admin1,x.country].filter(Boolean).join(', ')}));cache.set(key,out);return out;}
async function forecast({latitude,longitude,days=3,timezone='auto',signal}){days=Math.max(1,Math.min(14,+days||3));const url='https://api.open-meteo.com/v1/forecast?latitude='+encodeURIComponent(latitude)+'&longitude='+encodeURIComponent(longitude)+'&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,precipitation&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max&timezone='+encodeURIComponent(timezone||'auto')+'&forecast_days='+days;const d=await json(url,{timeout:8000,signal}),daily=d.daily||{},cur=d.current||{};const [currentIcon,currentSummary]=mapCode(cur.weather_code);return{current:{time:cur.time||'',icon:currentIcon,summary:currentSummary,temp:Math.round(cur.temperature_2m??0),feels:Math.round(cur.apparent_temperature??cur.temperature_2m??0),wind:Math.round(cur.wind_speed_10m??0),rain:Number(cur.precipitation??0)},days:(daily.time||[]).map((date,i)=>{const [icon,summary]=mapCode(daily.weather_code?.[i]);const dt=new Date(date+'T12:00:00');return{date,label:i===0?'Heute':i===1?'Morgen':i===2?'Übermorgen':dt.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'}),icon,summary,min:Math.round(daily.temperature_2m_min?.[i]??0),max:Math.round(daily.temperature_2m_max?.[i]??0),rain:Math.round(daily.precipitation_probability_max?.[i]??0),wind:Math.round(daily.wind_speed_10m_max?.[i]??0)};})};}
g.KCWeatherCore=Object.freeze({version:'0.2.0',searchPlaces,forecast,mapCode,knownPlaces:KNOWN});
})(window);
