/* KC Bilderrechner – frei bearbeitbare Geschichten
   Nur Texte zwischen den einfachen Anführungszeichen ändern.
   Kommas, Anführungszeichen und die äußere Struktur stehen lassen. */
window.KC_STORY_CONTENT={
 marc:{title:'Geschichte von Marc – Mein Weg über Grenzen hinweg',image:'../avatar-core/assets/chef/chef_male_neutral_armless_v0257.webp',text:[
 'Schön, dass du noch geblieben bist und mich noch ein bisschen näher kennenlernen möchtest.',
 'Nach meiner Ausbildung zog es mich hinaus in die Welt. Ich arbeitete zunächst in verschiedenen Restaurants und ging dann in die Schweiz. Dort lernte ich Küchen kennen, in denen Präzision, Ruhe und Verlässlichkeit selbst an langen Abenden selbstverständlich waren. Später führte mich mein Weg nach Frankreich. Zwischen neuen Gerichten, einer anderen Sprache und ungewohnten Arbeitsweisen begriff ich, wie viel man gewinnt, wenn man offen bleibt und voneinander lernt.',
 'Ein ganz besonderes Kapitel begann auf einem internationalen Kreuzfahrtschiff. Menschen aus vielen Ländern arbeiteten auf engem Raum zusammen, während draußen das Meer und jeden Morgen ein anderer Hafen warteten. In der Küche durfte niemand nur an sich selbst denken. Wenn einer ins Straucheln geriet, fing das Team ihn auf. Diese Zeit war anstrengend, manchmal überwältigend und zugleich voller Begegnungen, die ich nie vergessen habe.',
 'Irgendwann wollte ich meine Erfahrung dort einsetzen, wo gutes Essen nicht nur Genuss, sondern auch Sicherheit und Zuversicht bedeutet. Als Küchenleiter in einem Krankenhaus trug ich Verantwortung für viele Menschen. Hinter jedem Tablett stand ein Patient mit eigenen Sorgen, Hoffnungen und Bedürfnissen. Da wurde mir noch deutlicher: Eine Küche kann Wärme vermitteln, auch wenn man den Menschen, für den man kocht, nicht persönlich sieht.',
 'Später arbeitete ich in Einrichtungen der Behindertenhilfe. Dort begegnete ich Menschen, die mich mit ihrer Offenheit, ihrem Humor und ihrer Lebensfreude tief beeindruckten. Ich lernte, genauer hinzuhören, geduldiger zu sein und nicht zuerst auf Grenzen zu schauen, sondern auf das, was gemeinsam möglich ist.',
 'All diese Stationen haben mir gezeigt, dass gutes Arbeiten immer mit Respekt beginnt. Ob in der Schweiz, in Frankreich, auf See, im Krankenhaus oder in der Behindertenhilfe: Ein starkes Team entsteht dort, wo Menschen einander ernst nehmen, Verantwortung übernehmen und auch in schwierigen Momenten zusammenhalten.',
 'Genau deshalb bedeutet mir dein Einsatz für den Köcheclub Werne so viel. Auch auf einem vollen Weihnachtsmarkt zählt nicht nur, dass jeder Handgriff sitzt. Es zählt das freundliche Wort, die helfende Hand und das Gefühl, gemeinsam etwas Schönes für andere zu schaffen. Vielleicht wird es zwischendurch hektisch. Dann erinnere dich daran, dass niemand alles allein leisten muss.',
 'Dein Mitwirken im Köcheclub Werne kann dabei weit über einen einzelnen Einsatz hinausgehen. Hier können Freundschaften wachsen, neue Menschen einander kennenlernen und Erfahrungen von Generation zu Generation weitergegeben werden. Köchinnen und Köche tauschen Fachwissen aus, helfen sich gegenseitig und bilden eine eingeschworene Gemeinschaft, in der Verlässlichkeit und Kameradschaft zählen. Besonders wichtig ist mir das große soziale Engagement des Clubs: gemeinsam anpacken, andere unterstützen und Verantwortung für die Menschen in der Region übernehmen. Genau dafür stehen auch die Werte, die meinen eigenen Weg geprägt haben. Im Köcheclub soll jeder spüren, dass er dazugehört, gebraucht wird und gut aufgehoben ist.',
 'Ich hätte mich gefreut, einmal mit dir zusammenzuarbeiten – vielleicht beim Ausschank, an der Spülmaschine oder genau dort, wo gerade Unterstützung gebraucht wird. Menschen, die freiwillig Zeit schenken und andere nicht aus dem Blick verlieren, machen aus einem Arbeitseinsatz eine echte Gemeinschaft.',
 'Wenn du nach einem langen Tag müde, aber zufrieden nach Hause gehst, wirst du vielleicht spüren, was ich auf meinen Wegen gelernt habe: Die besten Erinnerungen entstehen selten durch Perfektion. Sie entstehen, wenn Menschen füreinander da sind.',
 'Danke, dass du noch geblieben bist und mir zugehört hast. Ich wünsche dir Mut, Freude und viele gute Begegnungen im Köcheclub Werne. Und wann immer diese Schulung wieder startet, bin ich gern wieder an deiner Seite.'
 ]},
 laura:{title:'Geschichte von Laura – Kochen mit Herz',image:'../avatar-core/assets/chef/chef_female_neutral_armless_v0257.webp',text:[
 'Schön, dass du noch geblieben bist und mich noch ein bisschen näher kennenlernen möchtest.',
 'Nach meiner Ausbildung bekam ich die Chance, in einem Sterne-Restaurant zu arbeiten. Dort lernte ich, wie aus hochwertigen Zutaten, viel Geduld und großer Sorgfalt etwas Besonderes entstehen kann. Jeder Teller musste stimmen. Doch am meisten beeindruckte mich, wie viele Menschen im Hintergrund zusammenwirkten, damit ein Gast am Ende einen schönen Abend erleben konnte.',
 'Danach arbeitete ich in verschiedenen Restaurants und großen Hotels. Ich begegnete Gästen aus aller Welt, erlebte festliche Abende und hektische Küchen, in denen innerhalb weniger Minuten viele Entscheidungen getroffen werden mussten. Diese Jahre machten mich sicherer und mutiger. Gleichzeitig wuchs in mir der Wunsch, mit meiner Arbeit Menschen zu erreichen, für die eine Mahlzeit noch eine ganz andere Bedeutung hat.',
 'So wechselte ich in ein Altenheim. Dort waren es nicht die Sterne über der Restauranttür, die zählten. Es waren die Augen der Bewohnerinnen und Bewohner, wenn ein vertrauter Duft Erinnerungen weckte. Manchmal erzählte mir jemand von einem Sonntagsessen aus der Kindheit oder von einem Rezept, das früher die ganze Familie an einen Tisch gebracht hatte. In solchen Momenten spürte ich, dass Essen Nähe schenken und ein Stück Zuhause zurückbringen kann.',
 'Später führte mich mein Weg in einen Kindergarten, weil mir das Wohlergehen von Kindern besonders am Herzen liegt. Kinder sind ehrlich: Was ihnen schmeckt, sieht man sofort. Aber hinter jeder Mahlzeit steckt auch Verantwortung. Sie soll guttun, Kraft geben und Freude machen. Ich liebte die neugierigen Fragen, das Lachen am Tisch und die kleinen Erfolge, wenn ein Kind etwas Neues probierte und stolz auf sich war.',
 'Diese unterschiedlichen Arbeitsplätze haben mich geprägt. In der Sterneküche lernte ich Genauigkeit, in Hotels Beweglichkeit, im Altenheim Aufmerksamkeit und bei den Kindern Geduld und Zuversicht. Überall galt dasselbe: Menschen möchten gesehen, respektiert und freundlich behandelt werden.',
 'Darum berührt mich dein freiwilliger Einsatz für den Köcheclub Werne. Auf dem Weihnachtsmarkt schenkst du nicht nur deine Arbeitszeit. Mit einem Lächeln, einem ruhigen Wort oder einer kleinen Hilfe kannst du dafür sorgen, dass sich Gäste und Kollegen willkommen fühlen. Gerade wenn viel los ist, zeigt sich, wie wertvoll Rücksicht und Zusammenhalt sind.',
 'Der Köcheclub Werne ist für mich ein Ort, an dem aus gemeinsamen Aufgaben echte Verbundenheit entstehen kann. Man lernt neue Menschen kennen, findet Freunde und kann Erfahrungen und Fachwissen miteinander teilen. Zugleich trägt eine eingeschworene Gemeinschaft auch durch anstrengende Tage: Man hört einander zu, hilft sich und freut sich gemeinsam über das Erreichte. Das große soziale Engagement des Clubs zeigt, dass Können und Mitgefühl zusammengehören. Genau diese Werte – Aufmerksamkeit, Verantwortung, Herzlichkeit und Zuversicht – haben auch meinen Weg bestimmt. Mein Wunsch ist, dass jeder Mensch sich im Köcheclub vom ersten Tag an willkommen, angenommen und gut aufgehoben fühlt. Und ich wünsche mir, dass dieses Miteinander über die ersten Tage hinaus weitergeführt wird: Auch wenn es einem einmal nicht gut geht, nehmen die anderen Rücksicht, hören zu und unterstützen, wo sie können.',
 'Ich hätte sehr gern einmal mit dir zusammengearbeitet. Vielleicht hätten wir in einem stressigen Moment kurz miteinander gelacht, uns gegenseitig Arbeit abgenommen und am Ende gemeinsam gesehen, was ein gutes Team schaffen kann. Solche Augenblicke sind oft leise – und bleiben trotzdem lange im Herzen.',
 'Vielleicht erinnerst du dich später einmal daran, wenn du einem Menschen mit einer kleinen Geste den Tag leichter machst. Für mich ist genau das gelebte Gastfreundschaft: aufmerksam sein, Mut machen und nach vorn schauen.',
 'Danke, dass du noch geblieben bist und mir zugehört hast. Ich wünsche dir von Herzen viele schöne Stunden, ein herzliches Miteinander und das gute Gefühl, Teil einer Gemeinschaft zu sein. Wenn diese Schulung wieder beginnt, begleite ich dich sehr gern erneut.'
 ]}
};
