const fs = require('fs');
const assert = require('assert');
const html = fs.readFileSync('pc-manager/index.html', 'utf8');
const catalog = fs.readFileSync('shared/pos-catalog-registry-v02946.js', 'utf8');
const health = fs.readFileSync('pc-manager/manager-select-health-v02946.js', 'utf8');
const renderer = fs.readFileSync('pc-manager/tv-shared-renderer-v02946.js', 'utf8');
const presentation = fs.readFileSync('tv-content/weihnachtsmarkt-2026/presentation.js', 'utf8');
const integration = fs.readFileSync('pc-manager/tv-weihnachtsmarkt-presentation.js', 'utf8');
const css = fs.readFileSync('pc-manager/styles.css', 'utf8');
assert(html.includes('pos-catalog-registry-v02946.js') && html.includes('manager-select-health-v02946.js') && html.includes('tv-shared-renderer-v02946.js'), 'Integrationsskripte fehlen');
['Getränke', 'Speisen', 'Pfand', 'Sonstiges', 'Happy Hour'].forEach(value => assert(catalog.includes(value), `Warengruppe fehlt: ${value}`));
assert((catalog.match(/p\('/g) || []).length >= 20, 'Kassenartikelkatalog unvollständig');
['tvWeatherDays', 'tvWeatherSource', 'tvWeatherRefresh', 'aCategory'].forEach(value => assert(health.includes(value), `Select-Reparatur fehlt: ${value}`));
assert(renderer.includes('configureMatrix') && renderer.includes('engine?.setMatrixSize') && renderer.includes("matrix(ticker, slide)"), 'Vorschau und Vorführung verwenden nicht dieselbe vollständige DisplayMatrix-Konfiguration');
assert(renderer.includes('KCTVContentObjectCore?.applyObjects'), 'Objektsichtbarkeit fehlt im gemeinsamen Renderer');
assert(renderer.includes("banner.dataset.tvObject = 'banner'") && renderer.includes("shape.dataset.tvObject = 'shape'"), 'Banner und Form sind nicht am gemeinsamen Greifersystem angemeldet');
assert(renderer.includes("register?.('tvSharedRenderer', VERSION)"), 'Renderer ist nicht am Release-Gate angemeldet');
assert(presentation.includes('backgroundPreset: "market-window-lights"'), 'Neuer Hintergrund ist nicht Standard');
assert(integration.includes("sourceVersion<'1.0.2'") && integration.includes("slide.backgroundPreset='market-window-lights'"), 'Vorhandene Weihnachtsmarktfolien werden nicht auf den neuen Hintergrund migriert');
assert(integration.includes('applyBackgroundPreset') && integration.includes('targets.forEach'), 'Hintergrundübernahme einzeln/für alle fehlt');
assert(renderer.includes('ensureTicker') && renderer.includes('displayMatrix?.enabled'), 'Laufschrift-/DisplayMatrix-Fallback fehlt im gemeinsamen Renderer (muss für PC-Vorschau UND TV-Vorführung identisch gelten)');
const mode=fs.readFileSync('pc-manager/tv-presentation-mode-extension.js','utf8');assert(!mode.includes('ensureRuntimeObjects'),'TV-Vorführung dupliziert den Laufschrift-Fallback erneut statt den gemeinsamen Renderer zu nutzen');
assert(css.includes('[data-tv-object="ticker"].kc-tv-display-matrix display-matrix-module'), 'DisplayMatrix-Größe gilt nicht für Vorschau und Vorführung');
assert(fs.existsSync('media/backgrounds/weihnachtsmarkt-werne-fensterlicht-v2.png'), 'Hintergrunddatei fehlt');
console.log('PASS catalog-select-shared-renderer: Hintergrundmigration und identische Typografie-/DisplayMatrix-Pipeline');
