const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8");
const adapter=read("pc-manager/tv-display-matrix-adapter.js");
const consolidation=read("pc-manager/tv-repair60-consolidation.js");
const workflow=read("pc-manager/tv-editor-workflow.js");
const menu=read("pc-manager/tv-object-context-menu-v02944.js");
const player=read("tv-player/weihnachtsmarkt-presentation-runtime.js");
const template=read("tv-content/weihnachtsmarkt-2026/presentation.js");
assert.match(adapter,/data-matrix-source/);
assert.match(adapter,/data-matrix-visible/);
assert.match(adapter,/data-matrix-design/);
assert.match(adapter,/textDrafts = new Map/);
assert.match(adapter,/event\.stopPropagation\(\)/);
assert.match(adapter,/data-matrix-commit/);
assert.match(adapter,/addEventListener\('blur', commitText\)/);
assert.match(adapter,/data-matrix-effect/);
assert.match(adapter,/Matrix-Spalten/);
assert.match(adapter,/pointerdown', claimTicker, true/);
assert.match(consolidation,/tickerEditorOwner = 'display-matrix-core'/);
assert.doesNotMatch(consolidation,/querySelectorAll\(':scope > \.kc-property-section/);
assert.match(consolidation,/Wetterkarten-Fläche/);
assert.match(consolidation,/Flackernde Kerze/);
assert.match(workflow,/customTextObjects=.*filter/);
assert.match(workflow,/delete s\.tableObject/);
assert.match(menu,/KCSelectionCore\?\.get/);
assert.match(player,/decorationObjects/);
assert.match(template,/rgba\(111,20,32,.92\)/);
assert.doesNotMatch(read("pc-manager/tv-table-reorder-extension.js"),/>Tabellenobjekt</);
console.log("PASS Repair 60: ein Laufschrift-Core, entprellte Eingabe, Del, Wetterfläche, TV-Symbole und Preislistenstil");
