const KEY="kc_tv_player_package";let data=JSON.parse(localStorage.getItem(KEY)||"null"),i=0,timer;const screen=document.getElementById("screen"),state=document.getElementById("state");const esc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));function article(s){return data?.catalogSnapshot?.find(a=>a.id===s.articleId)}let durchgang=0;
// Wie oft eine Folie drankommt: "jeder Durchgang", "jeder zweite", "jeder dritte" ...
// Der Versatz sorgt dafuer, dass sich zwei Folien mit demselben Takt nicht immer im selben
// Durchgang draengeln - sonst waeren manche Durchgaenge voll und andere fast leer.
function imDurchgang(s){
  const r=s.rotation||{};
  const jeder=Math.max(1,Number(r.every)||1);
  const versatz=Number(r.offset)||0;
  return (durchgang % jeder) === (versatz % jeder);
}
function active(){const now=new Date(),m=now.getHours()*60+now.getMinutes(),p=x=>{const[a,b]=String(x||"00:00").split(":").map(Number);return a*60+b};return(data?.slides||[]).filter(s=>s.enabled!==false&&imDurchgang(s)&&((p(s.start)<=p(s.end))?(m>=p(s.start)&&m<=p(s.end)):(m>=p(s.start)||m<=p(s.end))))}function fx(s){if(!s.animation||s.animation==="none")return"";const ch=s.animation.includes("snow")?"❄":s.animation==="stars"?"★":s.animation==="shooting-star"?"☄":"✦";return`<div class="tv-effect effect-${s.animation}">${Array.from({length:20},(_,n)=>`<i style="--x:${n*37%100}%;--y:${-10-(n%5)*8}%;--size:${14+n%5*5}px;--dur:${5+n%6}s;--delay:${-(n%9)*.5}s">${ch}</i>`).join("")}</div>`}function show(){clearTimeout(timer);const list=active();if(!list.length){if(durchgang<(data?.slides||[]).length){durchgang++;return show()}screen.innerHTML="<div><h1>Zurzeit keine Anzeige</h1><p>Das nächste Zeitprofil startet automatisch.</p></div>";timer=setTimeout(show,30000);return}i%=list.length;const s=list[i],a=article(s),title=s.title||a?.name||"",price=a?Number(a.price).toFixed(2).replace(".",",")+" €":s.price||"";const tr=KCDesignCorePresentation.normalize(s).transition?.type||"fade";screen.className=(s.theme||"club")+(s.type==="lcd"?" lcd":"")+" transition-"+tr;screen.innerHTML=`${fx(s)}<div><h1>${esc(title)}</h1><p>${esc(s.text)}</p>${price?`<div class="price">${esc(price)}</div>`:""}</div>${s.ticker?`<div class="ticker"><span>${esc(s.ticker)}</span></div>`:""}`;KCDesignCorePresentation.apply(screen,s);window.currentTvSlideData=s;timer=setTimeout(()=>{i=i+1;if(i>=list.length){i=0;durchgang++}show()},Math.max(3,Number(s.duration)||8)*1000)}document.getElementById("packageFile").onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!["KC-TV-1","kcm-tv-package-v2"].includes(d.schema))throw Error("Ungültiges Paketformat");data=d;window.currentTvPackageData=d;i=0;let persisted=true;try{localStorage.setItem(KEY,JSON.stringify(d))}catch(storageErr){persisted=false}state.textContent=(persisted?"Paket übernommen: ":"Paket wird abgespielt, aber NICHT dauerhaft gespeichert (Speichergrenze des Browsers überschritten, z.B. durch große Videos - nach einem Neustart bitte die Datei erneut einlesen): ")+(d.profile?.name||"");KCAudioPresentationCore?.play(data,{base:"../"});show()}catch(err){state.textContent="Importfehler: "+err.message}};document.getElementById("fullscreen").onclick=async()=>{await document.documentElement.requestFullscreen();document.getElementById("control").style.display="none"};if(data){window.currentTvPackageData=data;KCAudioPresentationCore?.play(data,{base:"../"});show()}else screen.innerHTML="<div><h1>Köcheclub Werne</h1><p>TV-Paket bitte einlesen</p></div>";

/* V0.29.10 – professional controls and reliable particle renderer */
(function(){
 const fontMap={system:'Arial,Helvetica,sans-serif',serif:'Georgia,"Times New Roman",serif',humanist:'"Trebuchet MS",Arial,sans-serif',rounded:'"Arial Rounded MT Bold",Arial,sans-serif',condensed:'"Arial Narrow",Arial,sans-serif',monospace:'Consolas,monospace'};
 function escx(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function effCfg(s){const d=KCDesignCorePresentation.normalize(s);d.effects=d.effects||{speed:1,density:2,size:1,opacity:.78,direction:'down'};return d.effects}
 function particleHTML(s){const effect=s.animation||'none';if(effect==='none')return'';const c=effCfg(s),density=Math.max(1,Math.min(5,+c.density||2)),count=effect.includes('heavy')?density*18:density*11;const chars={glitter:'✦','gold-dust':'◆','gold-rain':'◆',stars:'★','star-rain':'★',bokeh:'●','sparkle-wave':'✦','shooting-star':'☄'};const ch=effect.includes('snow')?'❄':(chars[effect]||'✦');const speed=Math.max(.35,Math.min(2.5,+c.speed||1)),size=Math.max(.5,Math.min(2,+c.size||1)),opacity=Math.max(.15,Math.min(1,+c.opacity||.78));let out='';for(let i=0;i<count;i++){const x=(i*47+13)%100,ps=Math.round((12+(i%7)*3)*size),dur=((4.2+(i%8)*.55)/speed).toFixed(2),delay=(-((i*0.63)%8)).toFixed(2),drift=((i%2?1:-1)*(12+(i%5)*5))+'vw',po=(opacity*(.55+(i%4)*.13)).toFixed(2);out+=`<i class="particle" style="--x:${x}%;--ps:${ps}px;--pd:${dur}s;--pdelay:${delay}s;--drift:${drift};--po:${po}">${ch}</i>`}return `<div class="tv-effect effect-${escx(effect)}">${out}</div>`}
 window.renderEffects=particleHTML;
 function applyPro(stage,s){if(!stage||!s)return;const d=KCDesignCorePresentation.normalize(s),t=d.typography||{};stage.style.setProperty('--font-family',fontMap[t.fontFamily]||fontMap.system);stage.style.setProperty('--title-weight',t.titleBold===false?'500':'800');stage.style.setProperty('--title-style',t.titleItalic?'italic':'normal');stage.style.setProperty('--title-transform',t.titleUppercase?'uppercase':'none');stage.style.setProperty('--text-weight',t.textBold?'700':'400');stage.style.setProperty('--text-style',t.textItalic?'italic':'normal');stage.style.setProperty('--price-weight',t.priceBold===false?'600':'900');stage.style.setProperty('--price-style',t.priceItalic?'italic':'normal');stage.style.setProperty('--letter-spacing',(+t.letterSpacing||0)+'em');stage.style.setProperty('--line-height',t.lineHeight||1.15);stage.style.setProperty('--text-align',t.textAlign||'center');stage.style.setProperty('--title-shadow',t.shadow===false?'none':'0 3px 15px rgba(0,0,0,.42)');stage.style.setProperty('--title-stroke',t.outline?'1px rgba(0,0,0,.5)':'0 transparent')}
 const oldRender=window.renderSlideInto;if(typeof oldRender==='function')window.renderSlideInto=function(screen,raw){oldRender(screen,raw);applyPro(screen,raw);const old=screen.querySelector('.tv-effect');if(old)old.outerHTML=particleHTML(raw)};
 const observer=new MutationObserver(()=>{document.querySelectorAll('#tvPreviewScreen,.preview').forEach(stage=>{const s=(typeof currentTvSlide==='function'?currentTvSlide():(window.slides&&window.slides[window.idx]))||null;if(s)applyPro(stage,s)})});observer.observe(document.documentElement,{childList:true,subtree:true});
 function bindAdvanced(box,s){if(!box||!s||box.querySelector('.pro-advanced'))return;const d=KCDesignCorePresentation.normalize(s),t=d.typography,e=d.effects;const isFonts=box.querySelector('[data-bind="design.typography.titleColor"]');const isSymbols=box.querySelector('[data-bind="animation"]');if(isFonts){const card=document.createElement('section');card.className='pro-editor-card pro-advanced';card.innerHTML=`<h4>Professionelle Typografie</h4><div class="pro-effect-grid"><label>Schriftfamilie<select data-pro="fontFamily"><option value="system">System / klar</option><option value="humanist">Humanistisch</option><option value="serif">Klassisch</option><option value="rounded">Rund</option><option value="condensed">Schmal / Plakat</option><option value="monospace">Technisch</option></select></label><label>Ausrichtung<select data-pro="textAlign"><option value="left">Links</option><option value="center">Zentriert</option><option value="right">Rechts</option></select></label><label>Buchstabenabstand<input data-pro="letterSpacing" type="range" min="-.02" max=".12" step=".01" value="${t.letterSpacing||0}"></label><label>Zeilenabstand<input data-pro="lineHeight" type="range" min=".9" max="1.6" step=".05" value="${t.lineHeight||1.15}"></label></div><div class="pro-toggle-row"><label><input data-pro="titleBold" type="checkbox" ${t.titleBold!==false?'checked':''}> Titel fett</label><label><input data-pro="titleItalic" type="checkbox" ${t.titleItalic?'checked':''}> Titel kursiv</label><label><input data-pro="titleUppercase" type="checkbox" ${t.titleUppercase?'checked':''}> Versalien</label><label><input data-pro="textBold" type="checkbox" ${t.textBold?'checked':''}> Text fett</label><label><input data-pro="textItalic" type="checkbox" ${t.textItalic?'checked':''}> Text kursiv</label><label><input data-pro="priceBold" type="checkbox" ${t.priceBold!==false?'checked':''}> Preis fett</label><label><input data-pro="priceItalic" type="checkbox" ${t.priceItalic?'checked':''}> Preis kursiv</label><label><input data-pro="shadow" type="checkbox" ${t.shadow!==false?'checked':''}> Schatten</label><label><input data-pro="outline" type="checkbox" ${t.outline?'checked':''}> Kontur</label></div>`;box.prepend(card);card.querySelector('[data-pro="fontFamily"]').value=t.fontFamily||'system';card.querySelector('[data-pro="textAlign"]').value=t.textAlign||'center';card.querySelectorAll('[data-pro]').forEach(i=>i.oninput=()=>{t[i.dataset.pro]=i.type==='checkbox'?i.checked:(i.type==='range'?+i.value:i.value);if(typeof saveTvPresentation==='function')saveTvPresentation();if(typeof renderTvPreview==='function')renderTvPreview();else if(typeof preview==='function')preview()})}
 if(isSymbols){const card=document.createElement('section');card.className='pro-editor-card pro-advanced';card.innerHTML=`<h4>Effektsteuerung</h4><div class="pro-effect-grid"><label>Effekt<select data-effect="type"><option value="none">Kein Effekt</option><option value="snow-light">Leichter Schneefall</option><option value="snow-heavy">Dichter Schneefall</option><option value="glitter">Feines Glitzern</option><option value="gold-dust">Goldregen</option><option value="stars">Sternenregen</option><option value="bokeh">Ruhige Lichtpunkte</option><option value="sparkle-wave">Glitzerwelle</option><option value="shooting-star">Sternschnuppen</option></select></label><label>Tempo<input data-effect="speed" type="range" min=".35" max="2.5" step=".05" value="${e.speed||1}"></label><label>Dichte<input data-effect="density" type="range" min="1" max="5" step="1" value="${e.density||2}"></label><label>Partikelgröße<input data-effect="size" type="range" min=".5" max="2" step=".1" value="${e.size||1}"></label><label>Deckkraft<input data-effect="opacity" type="range" min=".15" max="1" step=".05" value="${e.opacity||.78}"></label></div>`;box.prepend(card);card.querySelector('[data-effect="type"]').value=s.animation||'none';card.querySelectorAll('[data-effect]').forEach(i=>i.oninput=()=>{if(i.dataset.effect==='type')s.animation=i.value;else e[i.dataset.effect]=+i.value;if(typeof saveTvPresentation==='function')saveTvPresentation();if(typeof renderTvPreview==='function')renderTvPreview();else if(typeof preview==='function')preview()})}
 }
 const boxes=['tvContextEditor','contextEditor'].map(id=>document.getElementById(id)).filter(Boolean);boxes.forEach(box=>{new MutationObserver(()=>{const s=typeof currentTvSlide==='function'?currentTvSlide():(window.slides&&window.slides[window.idx]);if(s)requestAnimationFrame(()=>bindAdvanced(box,s))}).observe(box,{childList:true,subtree:true});const s=typeof currentTvSlide==='function'?currentTvSlide():(window.slides&&window.slides[window.idx]);if(s)bindAdvanced(box,s)});
})();
